services:
  db:
    image: postgres:16
    container_name: transac_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: transac_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - transac_db_data:/var/lib/postgresql/data

volumes:
  transac_db_data:
    driver: local
