name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['**']

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    name: Format, Lint, Build, Test, Audit (Rust)
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain (1.88.0) with components
        uses: dtolnay/rust-toolchain@1.88.0
        with:
          components: clippy, rustfmt

      - name: Cache cargo builds
        uses: Swatinem/rust-cache@v2

      - name: Verify formatting
        run: cargo fmt --all -- --check

      - name: Lint with clippy (deny warnings)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Build (all targets, all features)
        run: cargo build --workspace --all-targets --all-features

      - name: Generate lockfile if missing
        shell: bash
        run: |
          if [[ ! -f Cargo.lock ]]; then
            cargo generate-lockfile
          fi

      - name: Test (all features)
        run: cargo test --workspace --all-features -- --nocapture